### ISSUE TITLE
Improve CLI tracking instrumentation

### ISSUE THREAD

**Issue by rayshan** [bower/stats-bower#1]
What else can we track in order to broaden the breadth and depth of the insight we provide to the community?

- [x] Fix insight tracking for `search` command https://github.com/bower/bower/pull/1213
- [ ] `uninstall` & `prune` (for users to gauge relative popularity, e.g. Angular uninstalls vs Backbone installs in same time period) (need PR for Bower repo)
- [x] OS / node version (for publishers; GA relies on browser to report, need to track by URI/Event ID), see https://github.com/yeoman/insight/issues/12 (need PR for yeoman insight repo)
- [ ] errors (for publishers) (need PR for yeoman insight repo)
- [ ] opt-in / out %
- [x] bower CLI versions
